name: Pytest Allure (Disabled)

on:
  workflow_dispatch:  # workflow can only be run manually from the Actions tab

jobs:
  tests:
    if: ${{ false }}  # completely disables job even if triggered manually
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow is disabled. No tests will run."
