name: Pytest Allure

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps & Node (for allure-cli via npm)
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
      - name: Install allure-cli
        run: npm install -g allure-commandline@latest --no-audit --no-fund

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -n auto --alluredir=allure-results || true

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report || true

      - name: Upload Allure Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
